package com.example.dao;

import com.example.model.Movie;
import com.example.wpenia.phim.R;

import java.util.ArrayList;
import java.util.List;

public class DAOMovies {

    public List<Movie> getMovies(){
        List<Movie>movies = new ArrayList<>();
        DAOActores daoActores = new DAOActores();


        movies.add(new Movie("Ant-Man","2015","PG-13","29-06-2015","117 min", "Action","Peyton Reed", "Edward wright, Joe Cornish", daoActores.getActores(), "Armed with a super-suit with the astonishing ability to shrink in scale but increase in strength, cat burglar Scott Lang must embrace his inner hero and help his mentor, Dr. Hank Pym, plan and pull off a heist that will save the world.", "English", "1", "USA", R.drawable.antman,"7,3/10", "64", "7",1,"Film", R.drawable.antmantrailer));
        movies.add(new Movie("Infinity Wars","2018","PG-13","23-04-2018", "149 min","Action", "Anthony Russo, Joe Russo", "Christopher Markus, Stephen McFeely", daoActores.getActores(), "As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain. ", "English", "2", "USA", R.drawable.infinity, "8,6/10","68","10", 2, "Film",  R.drawable.videoimg));
        movies.add(new Movie("Iron Man","2008","PG-13","14-04-2008", "126 min","Action", " Jon Favreau", " Mark Fergus, Hawk Ostby ", daoActores.getActores(), "Tony Stark. Genius, billionaire, playboy, philanthropist. Son of legendary inventor and weapons contractor Howard Stark. When Tony Stark is assigned to give a weapons presentation to an Iraqi unit led by Lt. Col. James Rhodes, he's given a ride on enemy lines. That ride ends badly when Stark's Humvee that he's riding in is attacked by enemy combatants. He survives - barely - with a chest full of shrapnel and a car battery attached to his heart. In order to survive he comes up with a way to miniaturize the battery and figures out that the battery can power something else. Thus Iron Man is born. He uses the primitive device to escape from the cave in Iraq. Once back home, he then begins work on perfecting the Iron Man suit. But the man who was put in charge of Stark Industries has plans of his own to take over Tony's technology for other matters. ", "English", "6", "USA", R.drawable.iron1, "7,9/10", "79", "8", 3, "Film", R.drawable.antman));
        movies.add(new Movie("Iron Man 2","2010","PG-13","30-4-2010", "124 min","Action", "Peyton Reed", "Edwardwright, Joe Cornish", daoActores.getActores(), "With the world now aware of his identity as Iron Man, Tony Stark must contend with both his declining health and a vengeful mad man with ties to his father's legacy.", "English", "2", "USA", R.drawable.iron2, "7,0/10", "57", "7", 4, "Film", R.drawable.ironmantrailersec));
        movies.add(new Movie("Aladin","1992","G", "25-11-1992", "90 min","Animation", "Ron Clements, John Musker", "Ron Clements, John Musker, Ted Elliott, Terry Rossio", daoActores.getActores(), "When street rat Aladdin frees a genie from a lamp, he finds his wishes granted. However, he soon finds that the evil has other plans for the lamp -- and for Princess Jasmine. But can Aladdin save Princess Jasmine and his love for her after she sees that he isn't quite what he appears to be?", "English","15", "USA", R.drawable.aladin, "8/10", "86", "10", 5, "Film", R.drawable.aladdintrailer));
        movies.add(new Movie("Hotel Transylvania","2012", "PG", "08-09-2012", "91 min","Animation", "Genndy Tartakovsky", " Peter Baynham, Robert Smigel", daoActores.getActores(), "Dracula, who operates a high-end resort away from the human world, goes into overprotective mode when a boy discovers the resort and falls for the count's teenaged daughter.", "English", "1", "USA", R.drawable.hoteltransilvania, "7,1/10","47", "5",6, "Film", R.drawable.hoteltrailer));
        movies.add(new Movie("Cars","2006","PG", "09-06-2006", "116 min","Animation", "John Lasseter, Joe Ranft", "John Lasseter, Joe Ranft", daoActores.getActores(), "A hot-shot race-car named Lightning McQueen gets waylaid in Radiator Springs, where he finds the true meaning of friendship and family.", "English","12", "USA", R.drawable.cars, "7,1/10", "73", "5", 7, "Film", R.drawable.carstrailer));
        movies.add(new Movie("El Rey Leon","1994","G", "15-06-1994", "88 min","Animation", "Roger Allers, Rob Minkoff", "Irene Mecchi, Jonathan Roberts", daoActores.getActores(), "A Lion cub crown prince is tricked by a treacherous uncle into thinking he caused his father's death and flees into exile in despair, only to learn in adulthood his identity and his responsibilities.", "English", "11", "USA", R.drawable.reyleon, "8,5/10", "83", "10", 8, "Film", R.drawable.lionkingtrailer));
        movies.add(new Movie("Frozen","2013","PG", "22-11-2013", "102 min","Animation", "Chris Buck, Jennifer Lee", "Jennifer Lee", daoActores.getActores(), "When the newly-crowned Queen Elsa accidentally uses her power to turn things into ice to curse her home in infinite winter, her sister Anna teams up with a mountain man, his playful reindeer, and a snowman to change the weather condition.", "English", "37", "USA", R.drawable.frozen, "7,5/10","74", "4",9,"Film", R.drawable.frozentrailer ));
        movies.add(new Movie("Frozen 2","2019","PG", "22-11-2019", "NA","Animation", "Chris Buck, Jennifer Lee", "Jennifer Lee", daoActores.getActores(), "Plot unknown. This is the sequel to Walt Disney Pictures' 53rd full-length animated motion picture, Frozen (2013).", "English","NA", "USA", R.drawable.frozen2,"NA", "NA", "0", 10, "Film", R.drawable.frozentrailersec));
        movies.add(new Movie("Kung Fu Panda","2008","PG", "06-06-2008", "92 min","Animation", "Mark Osborne, John Stevenson", " Jonathan Aibel, Glenn Berger", daoActores.getActores(), "The Dragon Warrior has to clash against the savage Tai Lung as China's fate hangs in the balance. However, the Dragon Warrior mantle is supposedly mistaken to be bestowed upon an obese panda who is a novice in martial arts.", "English","14", "USA", R.drawable.kunfupanda, "7,6/10","73", "9", 11, "Film",R.drawable.kungfupandatrailer));
        movies.add(new Movie("Spideman","2017","PG-13", "28-06-2017", "133 min","Action", "Jon Watts", "Jonathan Goldstein, John Francis Daley ", daoActores.getActores(), "Peter Parker balances his life as an ordinary high school student in Queens with his superhero alter-ego Spider-Man, and finds himself on the trail of a new menace prowling the skies of New York City.", "English","5", "USA", R.drawable.spiderman, "7,5/10","73", "3",12,"Film",  R.drawable.spideytrailer));
        movies.add(new Movie("Capitan America","2011","PG-13", "19-04-2011", "124 min","Action", "Joe Johnston", "Christopher Markus (screenplay), Stephen McFeely", daoActores.getActores(), "Steve Rogers, a rejected military soldier transforms into Captain America after taking a dose of a Super-Soldier serum. But being Captain America comes at a price as he attempts to take down a war monger and a terrorist organization.", "English","3", "USA", R.drawable.captain, "6,9/10","66","8", 13,"Film", R.drawable.captamericatrailer));
        movies.add(new Movie("Ant-Man and The Wasp","2018","PG-13","06-07-2018", "118 min","Action", "Peyton Reed", "Chris McKenna, Erik Sommers", daoActores.getActores(), "In the aftermath of Captain America: Civil War (2016), Scott Lang grapples with the consequences of his choices as both a superhero and a father. As he struggles to rebalance his home life with his responsibilities as Ant-Man, he's confronted by Hope van Dyne and Dr. Hank Pym with an urgent new mission. Scott must once again put on the suit and learn to fight alongside The Wasp as the team works together to uncover secrets from their past.", "English", "1", "USA", R.drawable.wasp,"7,2/10", "70", "11", 14, "Film", R.drawable.antmanwasptrailer));
        return  movies;

    }

}
