package com.example.dao;

import com.example.model.Movie;
import com.example.wpenia.phim.R;

import java.util.ArrayList;
import java.util.List;

public class DAOMovies {

    public List<Movie> getMovies(){
        List<Movie>movies = new ArrayList<>();
        DAOActores daoActores = new DAOActores();


        movies.add(new Movie(1,"Ant-Man","2015","PG-13","Action", "Peyton Reed", "Edward wright, Joe Cornish", daoActores.getActores(), "Armed with a super-suit with the astonishing ability to shrink in scale but increase in strength, cat burglar Scott Lang must embrace his inner hero and help his mentor, Dr. Hank Pym, plan and pull off a heist that will save the world.", "1", "USA", "64", "1h 57 min", R.drawable.antmantrailer, "7,3/10"));
        movies.add(new Movie(2,"Infinity Wars","2018","PG-13","Action", "Anthony Russo, Joe Russo", "Christopher Markus, Stephen McFeely", daoActores.getActores(), "As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain. ", "1", "USA", "68", "2h 29 min", R.drawable.videoimg, "8,6/10"));
        movies.add(new Movie(3,"Iron Man","2008","PG-13","Action", " Jon Favreau", " Mark Fergus, Hawk Ostby ", daoActores.getActores(), "Tony Stark. Genius, billionaire, playboy, philanthropist. Son of legendary inventor and weapons contractor Howard Stark. When Tony Stark is assigned to give a weapons presentation to an Iraqi unit led by Lt. Col. James Rhodes, he's given a ride on enemy lines. That ride ends badly when Stark's Humvee that he's riding in is attacked by enemy combatants. He survives - barely - with a chest full of shrapnel and a car battery attached to his heart. In order to survive he comes up with a way to miniaturize the battery and figures out that the battery can power something else. Thus Iron Man is born. He uses the primitive device to escape from the cave in Iraq. Once back home, he then begins work on perfecting the Iron Man suit. But the man who was put in charge of Stark Industries has plans of his own to take over Tony's technology for other matters. ", "1", "USA", "64", "1h 57 min", R.drawable.antman, "7,3/10"));
        movies.add(new Movie(4,"Iron Man 2","2015","PG-13","Action", "Peyton Reed", "Edwardwright, Joe Cornish", daoActores.getActores(), "Armed with a super-suit with the astonishing ability to shrink in scale but increase in strength, cat burglar Scott Lang must embrace his inner hero and help his mentor, Dr. Hank Pym, plan and pull off a heist that will save the world.", "1", "USA", "64", "1h 57 min", R.drawable.ironmantrailersec, "7,3/10"));
        movies.add(new Movie(5,"Aladin","2015","PG-13","Action", "Peyton Reed", "Edwardwright, Joe Cornish", daoActores.getActores(), "Armed with a super-suit with the astonishing ability to shrink in scale but increase in strength, cat burglar Scott Lang must embrace his inner hero and help his mentor, Dr. Hank Pym, plan and pull off a heist that will save the world.", "1", "USA", "64", "1h 57 min", R.drawable.aladdintrailer, "7,3/10"));
        movies.add(new Movie(6,"Hotel Transylvania","2015","PG-13","Action", "Peyton Reed", "Edwardwright, Joe Cornish", daoActores.getActores(), "Armed with a super-suit with the astonishing ability to shrink in scale but increase in strength, cat burglar Scott Lang must embrace his inner hero and help his mentor, Dr. Hank Pym, plan and pull off a heist that will save the world.", "1", "USA", "64", "1h 57 min", R.drawable.hoteltrailer, "7,3/10"));
        movies.add(new Movie(7,"Cars","2015","PG-13","Action", "Peyton Reed", "Edwardwright, Joe Cornish", daoActores.getActores(), "Armed with a super-suit with the astonishing ability to shrink in scale but increase in strength, cat burglar Scott Lang must embrace his inner hero and help his mentor, Dr. Hank Pym, plan and pull off a heist that will save the world.", "1", "USA", "64", "1h 57 min", R.drawable.carstrailer, "7,3/10"));
        movies.add(new Movie(8,"El Rey Leon","2015","PG-13","Action", "Peyton Reed", "Edwardwright, Joe Cornish", daoActores.getActores(), "Armed with a super-suit with the astonishing ability to shrink in scale but increase in strength, cat burglar Scott Lang must embrace his inner hero and help his mentor, Dr. Hank Pym, plan and pull off a heist that will save the world.", "1", "USA", "64", "1h 57 min", R.drawable.lionkingtrailer, "7,3/10"));
        movies.add(new Movie(9,"Frozen","2015","PG-13","Action", "Peyton Reed", "Edwardwright, Joe Cornish", daoActores.getActores(), "Armed with a super-suit with the astonishing ability to shrink in scale but increase in strength, cat burglar Scott Lang must embrace his inner hero and help his mentor, Dr. Hank Pym, plan and pull off a heist that will save the world.", "1", "USA", "64", "1h 57 min", R.drawable.frozentrailer, "7,3/10"));
        movies.add(new Movie(10,"Frozen 2","2015","PG-13","Action", "Peyton Reed", "Edwardwright, Joe Cornish", daoActores.getActores(), "Armed with a super-suit with the astonishing ability to shrink in scale but increase in strength, cat burglar Scott Lang must embrace his inner hero and help his mentor, Dr. Hank Pym, plan and pull off a heist that will save the world.", "1", "USA", "64", "1h 57 min", R.drawable.frozentrailersec, "7,3/10"));
        movies.add(new Movie(11,"Kung Fu Panda","2015","PG-13","Action", "Peyton Reed", "Edwardwright, Joe Cornish", daoActores.getActores(), "Armed with a super-suit with the astonishing ability to shrink in scale but increase in strength, cat burglar Scott Lang must embrace his inner hero and help his mentor, Dr. Hank Pym, plan and pull off a heist that will save the world.", "1", "USA", "64", "1h 57 min", R.drawable.kungfupandatrailer, "7,3/10"));
        movies.add(new Movie(12,"Spideman","2015","PG-13","Action", "Peyton Reed", "Edwardwright, Joe Cornish", daoActores.getActores(), "Armed with a super-suit with the astonishing ability to shrink in scale but increase in strength, cat burglar Scott Lang must embrace his inner hero and help his mentor, Dr. Hank Pym, plan and pull off a heist that will save the world.", "1", "USA", "64", "1h 57 min", R.drawable.spideytrailer, "7,3/10"));
        movies.add(new Movie(13,"Capitan America","2015","PG-13","Action", "Peyton Reed", "Edwardwright, Joe Cornish", daoActores.getActores(), "Armed with a super-suit with the astonishing ability to shrink in scale but increase in strength, cat burglar Scott Lang must embrace his inner hero and help his mentor, Dr. Hank Pym, plan and pull off a heist that will save the world.", "1", "USA", "64", "1h 57 min", R.drawable.captamericatrailer, "7,3/10"));
        movies.add(new Movie(14,"Ant-Man and The Wasp","2015","PG-13","Action", "Peyton Reed", "Edwardwright, Joe Cornish", daoActores.getActores(), "Armed with a super-suit with the astonishing ability to shrink in scale but increase in strength, cat burglar Scott Lang must embrace his inner hero and help his mentor, Dr. Hank Pym, plan and pull off a heist that will save the world.", "1", "USA", "64", "1h 57 min", R.drawable.antmanwasptrailer, "7,3/10"));
        return  movies;

    }

}
